#!/bin/sh
#
# 2013-2015 ungleich GmbH (cdist at ungleich.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os="$(cat "$__global/explorer/os")"
case "$os" in
    centos)
        restart="/etc/init.d/nginx reload"
    ;;
    debian)
        restart="systemctl restart nginx"
    ;;
    *)
        echo "Unsupported OS: $os" >&2
        exit 1
    ;;
esac

if grep -E -q "^(__file|__link)/etc/nginx" "$__messages_in"; then
    echo $restart
fi
