#!/bin/sh
#
# 2013-2017 ungleich GmbH (cdist at ungleich.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

config_name="$(cat "$__object/parameter/config")"
# Strip away any leading slashes
config="${config_name##*/}"

os="$(cat "$__global/explorer/os")"
os_version="$(cat "$__global/explorer/os_version")"
case "$os" in
    centos)
        restart="/etc/init.d/nginx reload"
    ;;
    debian)
        case "$os_version" in
            [1-7]*)
                restart="/etc/init.d/nginx restart"
            ;;
            *)
                restart="systemctl restart nginx"
            ;;
        esac
    ;;
    devuan)
        restart="/etc/init.d/nginx restart"
    ;;
    *)
        echo "Unsupported OS: $os" >&2
        exit 1
    ;;
esac

destination=/etc/nginx/

# Create 48 bit random key for nginx
if [ -f "$__object/parameter/ssl-cert" ] || [ -f "$__object/parameter/ssl-key" ] || [ -f "$__object/parameter/ssl"]; then
cat <<eof
    if [ ! -f "${destination}nginx-ticketkey" ]; then
        echo "head -c 48 /dev/urandom > ${destination}nginx-ticketkey"
    fi
eof
fi

# Create the Diffie-Hellman key

dh=$(cat "$__object/parameter/dh")

cat <<eof
    if [ ! -f "${destination}dhparam.pem" ]; then
        echo "openssl dhparam -outform PEM -out ${destination}/dhparam.pem $dh"
    fi
eof

if grep -E -q "^(__file|__link)/etc/nginx" "$__messages_in"; then
    echo $restart
fi
